[package]
name = "aoc-2025-9"
version = "1.84.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.16.1"

[[bin]]
name = "aoc-2025-9"
path = "main.rs"
